### ISSUE TITLE
Specifying the --port flag seems to have no effect

### ISSUE THREAD

**Issue by b0ri5** [johnpapa/lite-server#5] opened 2015-12-24 02:34 UTC
The --port flag seems to have no effect:
$ lite-server --verbose --port=8081
options { port: 8081,
  openPath: '.',
  files: [ './**/*.html', './**/*.css', './**/*.js' ],
  baseDir: './',
  fallback: '/./index.html' }
[BS] Access URLs:
 --------------------------------------
       Local: http://localhost:3000
    External: http://<my-ip>:3000
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://<my-ip>:3001
 --------------------------------------

So the console output looks as though the server is listening on ports 3000 and 3001 and netstat supports that:
$ netstat -at
tcp6       0      0 [::]:3000               [::]:*                  LISTEN     
tcp6       0      0 [::]:3001               [::]:*                  LISTEN 

Does browser-sync not support the port option properly?

**Comment by Lacka90** [comment] 2015-12-26 09:51
lite-server --port 3000

**Comment by adambuczynski** [comment] 2015-12-27 05:52
I have the same issue.

```
./node_modules/lite-server/bin/lite-server --port 8080 --baseDir './public'
[BS] Access URLs:
 -------------------------------------
       Local: http://localhost:3000
```

**Comment by adambuczynski** [comment] 2016-01-11 23:39
Seems to have fixed itself now.

**Comment by johnpapa** [comment] 2016-01-19 18:34
it is now fixed.

**Comment by ramswaroop** [comment] 2016-02-02 16:51
Specifying the port in `bs-config.js` or `bs-config.json` doesn't work too. Is this issue fixed too?

**Comment by mikeerickson** [comment] 2016-02-02 21:32
@ramswaroop I am using port configuration in bs-config.json and it works fine for me

**Comment by cgmartin** [comment] 2016-02-03 02:56
@ramswaroop I am also unable to reproduce. Pls share the first 15 lines of log output from running `lite-server` and the contents of your `bs-config.js` or `bs-config.json` and we can help troubleshoot.

**Comment by ramswaroop** [comment] 2016-02-03 06:22
My `bs-config.js` is:
```javascript
{
   port: 7000
}
```
and I have this file in the directory from where lite-server is serving files from i.e, `./` . Below is the log:

```
lite-server --open dist

[BS] Access URLs:
 ----------------------------------------
       Local: http://localhost:3000
    External: http://192.168.104.190:3000
 ----------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.104.190:3001
 ----------------------------------------
[BS] Serving files from: ./
[BS] Watching files...
16.02.02 20:02:59 200 GET /dist/index.html (Unknown - 29ms)
16.02.02 20:03:00 200 GET /dist/css/style.min.css (Unknown - 8ms)
16.02.02 20:03:00 200 GET /node_modules/angular-material/angular-material.min.css (Unknown - 11ms)
16.02.02 20:03:00 200 GET /dist/img/logo.png (Unknown - 3ms)
16.02.02 20:03:00 200 GET /node_modules/angular/angular.min.js (Unknown - 6ms)
16.02.02 20:03:00 200 GET /node_modules/angular-route/angular-route.min.js (Unknown - 4ms)
16.02.02 20:03:00 200 GET /node_modules/angular-cookies/angular-cookies.min.js (Unknown - 4ms)
```

**Comment by cgmartin** [comment] 2016-02-03 13:36
@ramswaroop two issues I see from your output...

An older `lite-server` version seems to be in use, as I don't see the new log messages that were added in `2.0.1`. 

To check your lite-server version:
```
# If installed globally
$ npm -g ls lite-server
/Users/myhome/.npm-packages/lib
└── lite-server@2.0.1 

# or if used from local project
$ npm ls lite-server
angular2-tour-of-heroes@0.0.1 /Users/myhome/Src/angular2-sandbox/angular2-tour-of-heroes
└── lite-server@2.0.1  -> /Users/myhome/.npm-packages/lib/node_modules/lite-server
```

To install the new version:
```
# To update globally
$ npm install -g lite-server@latest

# To update in local project
$ npm install --save-dev lite-server@latest
```

The other issue is in the `bs-config.json`, it isn't in a JSON format that Node.js will handle by default. Quotes must be added around all field properties. i.e.:
```
{ "port": 8000 }
```

Or else you will get an error similar to:
```
$ lite-server
/Users/myhome/.npm-packages/lib/node_modules/lite-server/lib/lite-server.js:28
    throw(err);
    ^

SyntaxError: /Users/cmartin/Src/angular2-sandbox/angular2-tour-of-heroes/bs-config.json: Unexpected token p
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:450:27)
    at Module.load (module.js:356:32)
...
```

Hope this helps

**Comment by johnpapa** [comment] 2016-02-03 13:37
BTW - we recommend using it locally, not globally. But its always your call :)

**Comment by ramswaroop** [comment] 2016-02-03 14:09
@cgmartin Okay, I will try this after updating lite-server (installed locally). Meanwhile, can you tell me how is my `bs-config.js` incorrect? It is a `js` file so I have defined the config as a `js object` rather than a `JSON object`. This is what I assumed from `bs-config.js` and `bs-config.json` but I guess both require a `JSON object`.

**Comment by cgmartin** [comment] 2016-02-03 14:16
@ramswaroop OK, I didn't look closely at your file name... the contents made me think it was a `.json` file.

To use the `bs-config.js` format, just make sure to export it just like any other Node.js module:
```
module.export = { port: 8000 };   // quotes around field properties not required here
```

**Comment by ramswaroop** [comment] 2016-02-03 14:23
@cgmartin It's okay, no problem. By the way it's still not working after update. Below are the logs:
```
> iw-analytics-fe@0.1.0 lite /Users/ramswaroop/Documents/Workspace/iw-analytics-fe
> lite-server --open dist

** browser-sync options **
{ injectChanges: false,
  files: [ './**/*.{html,htm,css,js}' ],
  server: { baseDir: './', middleware: [ [Function], [Function] ] } }
[BS] Access URLs:
 ----------------------------------------
       Local: http://localhost:3000
    External: http://192.168.104.190:3000
 ----------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.104.190:3001
 ----------------------------------------
[BS] Serving files from: ./
[BS] Watching files...
16.02.03 19:51:17 404 GET /index.html
```
I guess now the `--open` option isn't working :p

**Comment by cgmartin** [comment] 2016-02-03 14:32
@ramswaroop The options displayed in your log output don't show any customizations other than the defaults...

- Your `bs-config.js` file should be located in the same directory as the your project
- The new `lite-server` version does not use any CLI arguments that the old version did, such as `--open`.  Every option must be put in the `bs-config` override file.

**Comment by cgmartin** [comment] 2016-02-03 14:33
Everything should be documented in the README, but let us know if something isn't clear there.

**Comment by ramswaroop** [comment] 2016-02-03 14:47
@cgmartin Thanks for the help, it is working now. 

The documentation is clear enough but I couldn't find anywhere that the new version doesn't support command line options. May be I didn't read properly. 

But I am having problems with the `open` option now. My `bs-config.json` file is like:
```js
{
  "port": 8989,
  "open": "dist"
}
```
And my log is like:
```
> iw-analytics-fe@0.1.0 lite /Users/ramswaroop/Documents/Workspace/iw-analytics-fe
> lite-server

** browser-sync options **
{ injectChanges: false,
  files: [ './**/*.{html,htm,css,js}' ],
  server: { baseDir: './', middleware: [ [Function], [Function] ] },
  port: 8989,
  open: 'dist' }
[BS] Access URLs:
 ----------------------------------------
       Local: http://localhost:8989
    External: http://192.168.104.190:8989
 ----------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.104.190:3001
 ----------------------------------------
[BS] Serving files from: ./
[BS] Watching files...
16.02.03 20:15:21 404 GET /index.html
```

Earlier I used the same value in the `--open` option in command line and it worked. Can you figure out what can be the issue now?

**Comment by cgmartin** [comment] 2016-02-03 16:06
@ramswaroop the absence of CLI options in the README essentially communicates that there are no CLI options available ;) The breaking changes could be better communicated in a CHANGELOG, which we're missing.

Your `open:` option seems correct based on the log output and browsersync's docs:
https://www.browsersync.io/docs/options/#option-open

What problems are you having with it?

**Comment by ramswaroop** [comment] 2016-02-04 10:26
@cgmartin But if you see the last line in the log, it says it can't find `index.html`. Gives a `404` error, but earlier, the same value for `--open` worked properly.

**Comment by cgmartin** [comment] 2016-02-04 13:37
I think the confusion is related to the behavior of the earlier version's CLI arguments. The `--open` arg from v1 lite-server is not the same as the `open:` property in v2/bs-config.

Just to confirm, your intent is to change the base directory of your source files? If so, give this a try:
```
{
  "port": 8989,
  "server": { "baseDir": "dist" } 
}
```

lite-server v2 removed all of the v1 CLI arg magic. The best resource now for changing the custom behavior is the [Browsersync docs](https://www.browsersync.io/docs/options/).

**Comment by ramswaroop** [comment] 2016-02-05 10:58
@cgmartin Options `baseDir` and `open` are different according to v1. The former means the root directory from where the server will serve files from and the latter refers to the file which the server will open first when it starts.

**Comment by JakeFalcor** [comment] 2016-02-10 00:14
@cgmartin I just slammed the same issue that others had here - my configuration file had no effect even though lite-server readme stated it was the correct way to do it. After a couple of looks into the library I realized that a new major version was out.

Would it be ok if a note was added to readme that this behaviour was added in 2.0.0?

**Comment by johnpapa** [comment] 2016-04-04 16:11
always feel free to make a PR suggestion

**Closed by johnpapa** 2016-04-04 16:11 UTC

**Comment by sanderboer** [comment] 2016-07-16 09:28
On windows10, using above's example:
```
``C:\R102-occ-devenv\emcc-webgl\bs-config.js:2
  "port": 8989,
        ^

SyntaxError: Unexpected token :
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at start (C:\R102-occ-devenv\emcc-webgl\node_modules\lite-server\lib\lite-server.js:27:17)
```

Using module.export does not throw an error, but ignores the settings.

S

**Comment by softdays** [comment] 2016-09-08 17:46
Same problem using Windows 8.1:
```
myProject\scripts\bs-config.js:2
        "port": 8000
              ^

SyntaxError: Unexpected token :
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at start (myProject\node_modules\lite-server\lib\lite-server.js:27:17)
    at Object.<anonymous> (D:\dev\projects\evaluation\workspace\evaluation-paren
t\evaluation-frontend\node_modules\lite-server\bin\lite-server:7:30)
    at Module._compile (module.js:409:26)
```
Here is my json config:
```
{
	"port": 8000
}
```
I'm using lite-server@2.2.2,  npm@2.15.8, node@v4.4.7

**Comment by mcmellawatt** [comment] 2016-09-20 19:26
+1...also experiencing the same behavior described above by @softdays and @sanderboer on Windows 10.

**Comment by mcmellawatt** [comment] 2016-09-20 19:34
Fixed the issue by using a .json file instead of a .js file.  I should have read it more closely, but I think the "Custom Configuration" section of the documentation could be a little clearer.

It says:

"You can provide custom path to your config file via -c or --config= run time options:
lite-server -c configs/my-bs-config.js"

and then goes on to say:

"For example, to change the server port, watched file paths, and base directory for your project, create a bs-config.json
{
  "port": 8000,
  "files": ["./src/**/*.{html,htm,css,js}"],
  "server": { "baseDir": "./src" }
}"

I just glanced at the example command and then the example config contents without noting the change in file type.  User error on my part for sure, but it could be a bit more obvious in the doc.

**Comment by maverick-io** [comment] 2020-05-08 00:18
Did not detect a `bs-config.json` or `bs-config.js` override file. Using lite-server defaults...
** browser-sync config **
{
  injectChanges: false,
  files: [ './**/*.{html,htm,css,js}' ],
  watchOptions: { ignored: 'node_modules' },
  server: { baseDir: './', middleware: [ [Function], [Function] ] }
}
[Browsersync] Access URLs:
 -------------------------------------
       Local: http://localhost:3000
    External: http://192.168.56.1:3000
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://localhost:3001
 -------------------------------------
[Browsersync] Serving files from: ./
[Browsersync] Watching files...
20.05.08 05:26:20 200 GET /index.html
20.05.08 05:26:25 200 GET /index.html
20.05.08 05:26:30 200 GET /index.html
20.05.08 05:26:36 200 GET /index.html
20.05.08 05:26:41 200 GET /index.html
20.05.08 05:26:46 200 GET /index.html






its watching the files  but doesn't show anything on localhost:3000

(web not available)
