### ISSUE TITLE
Installing lite-server error Can't find python executable

### ISSUE THREAD

**Issue by pthalacker** [johnpapa/lite-server#34] opened 2016-02-13 00:22 UTC
I am unable to install lite-server.  I get an error that node-gyp can't find the python executable.  The only solution I find online is to install python and C++ and Windows SDK and build it from scratch.  Am I missing something?

**Comment by billfranklin** [comment] 2016-02-22 19:50
I too am having that error appear during the install

**Comment by johnpapa** [comment] 2016-03-07 23:39
probably a problem with installing other node modules too, right? we need more info to know what the issue is

**Comment by pthalacker** [comment] 2016-03-07 23:43
Nope.  lite-server is the only module I have ever had this problem with.  I switched to http-server to avoid the problem,

**Comment by johnpapa** [comment] 2016-03-07 23:44
If you have more info, we can look into it.

**Comment by pthalacker** [comment] 2016-03-07 23:46
When I get a chance I will re run it and upload the error output

**Comment by jjhampton** [comment] 2016-03-14 18:07
I don't think this is an issue specifically w/ Lite Server, but is related to an issue that an issue that node-gyp has on Windows - apparently it is one of Browser-sync's dependencies.

See this (long) thread for a solution - you may have to install the C++ build tools and Python 2.7 as I did.

**Comment by johnpapa** [comment] 2016-06-22 11:17
seems that is the case. closing

**Closed by johnpapa** 2016-06-22 11:17 UTC
